version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: construction_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: construction_management
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - construction_network

networks:
  construction_network:
    driver: bridge

volumes:
  mariadb_data: